/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PresentationsRouteImport } from './routes/presentations'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as NotificationsHistoryRouteImport } from './routes/notifications-history'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ImportImagesRouteImport } from './routes/import-images'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsRoute = PresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsHistoryRoute = NotificationsHistoryRouteImport.update({
  id: '/notifications-history',
  path: '/notifications-history',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportImagesRoute = ImportImagesRouteImport.update({
  id: '/import-images',
  path: '/import-images',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/import-images': typeof ImportImagesRoute
  '/notifications': typeof NotificationsRoute
  '/notifications-history': typeof NotificationsHistoryRoute
  '/preferences': typeof PreferencesRoute
  '/presentations': typeof PresentationsRoute
  '/settings': typeof SettingsRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/import-images': typeof ImportImagesRoute
  '/notifications': typeof NotificationsRoute
  '/notifications-history': typeof NotificationsHistoryRoute
  '/preferences': typeof PreferencesRoute
  '/presentations': typeof PresentationsRoute
  '/settings': typeof SettingsRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/import-images': typeof ImportImagesRoute
  '/notifications': typeof NotificationsRoute
  '/notifications-history': typeof NotificationsHistoryRoute
  '/preferences': typeof PreferencesRoute
  '/presentations': typeof PresentationsRoute
  '/settings': typeof SettingsRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/import-images'
    | '/notifications'
    | '/notifications-history'
    | '/preferences'
    | '/presentations'
    | '/settings'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalog'
    | '/import-images'
    | '/notifications'
    | '/notifications-history'
    | '/preferences'
    | '/presentations'
    | '/settings'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/import-images'
    | '/notifications'
    | '/notifications-history'
    | '/preferences'
    | '/presentations'
    | '/settings'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  ImportImagesRoute: typeof ImportImagesRoute
  NotificationsRoute: typeof NotificationsRoute
  NotificationsHistoryRoute: typeof NotificationsHistoryRoute
  PreferencesRoute: typeof PreferencesRoute
  PresentationsRoute: typeof PresentationsRoute
  SettingsRoute: typeof SettingsRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications-history': {
      id: '/notifications-history'
      path: '/notifications-history'
      fullPath: '/notifications-history'
      preLoaderRoute: typeof NotificationsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-images': {
      id: '/import-images'
      path: '/import-images'
      fullPath: '/import-images'
      preLoaderRoute: typeof ImportImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  ImportImagesRoute: ImportImagesRoute,
  NotificationsRoute: NotificationsRoute,
  NotificationsHistoryRoute: NotificationsHistoryRoute,
  PreferencesRoute: PreferencesRoute,
  PresentationsRoute: PresentationsRoute,
  SettingsRoute: SettingsRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
